### ISSUE TITLE
[edge compute] Update the agent to trigger the poll request on the leader only

### ISSUE THREAD

**Issue by deviantony** [portainer/agent#117]
When running inside a Swarm cluster, the agent should only trigger the short poll request on the node that is the leader of the Swarm cluster.

This will allow us to avoid spamming poll requests from all the nodes in the cluster and to make sure that we're always reaching out to a manager node.

We'll leverage Swarm cluster failover as well.

**Comment by chiptus** [comment]
To check if a node is a leader we can use `cli.NodeInspectWithRaw`. the returned object has `ManagerStatus` which has a boolean property `Leader`.

We need to check if a node is a leader before polling. We can also disable the `startStatusPollLoop` is it's not a leader, but I actually think it useful to leave this function running, and check for leader status every run. This way if the leader is off, the next leader will trigger the poll the next time because its status will change.

Otherwise, we will still need some polling of the docker API to check if the status was changed

**Comment by chiptus** [comment]
Changes are needed only for a swarm cluster and for a non-leader node.
A leader should continue as usual.

For a non-leader node we need to have a place that polls for changes in the status. When the node becomes a leader - run `Operator.Start()`

**Comment by chiptus** [comment]
As I see it the best place to do this would be`enableEdgeMode` function. we should add a function `isLeaderNode`. my first thought was to the cluster service, but since it's not related to docker, I guess it's not the place. so maybe to docker.InfoService.

inside `enableEdgeMode` if node is a leader, the operator will start. otherwise, there will be a poll every x seconds that check if status was changed, and if true, it will start

**Comment by chiptus** [comment]
what happens if the current node was the leader, but it was demoted? should we leave the leader polling active, and stop the tunnelOperator in this case?

**Comment by deviantony** [comment]
Closed via #120
