### ISSUE TITLE
Edge Agent makes assumptions about swarm mode

### ISSUE THREAD

**Issue by SvenDowideit** [portainer/agent#69]
I have a system in my network that has docker swarm mode enabled, but is not the system that the portainer server is running on.

when I use `docker run` to start an edge agent on this host, it complains that it needs `AGENT_CLUSTER_ADDR` set. 

In this case, I want to have a non-swarm cluster agent...

**Comment by deviantony** [comment]
@SvenDowideit The agent automatically detects if it is running inside a Swarm cluster and if so, requires the `AGENT_CLUSTER_ADDR` to be configured to be able to form an agent cluster (even for a single node cluster). 

Deploy the agent as a service and it will be fine. I'm gonna create another issue as I've identified a way to give a default value for this environment variable.

**Comment by SvenDowideit** [comment]
@deviantony  I think you missunderstood - I need this agent to _not_ insist that its in swarm mode. The fact this node is _for other purposes_ set to enable swarm has nothing to do with how this node should be used by portainer.

I use the same nodes for multiple projects - this notebook is used for testing $work related swarm things, and for non-$ volunteer things for working on very non-swarm related things. TBH, one of them will likely run 2 agents, talking to different portainers.

**Comment by deviantony** [comment]
@SvenDowideit what prevents you from simply deploying the agent as a service on that node?

**Comment by SvenDowideit** [comment]
this issue is closed - so as a user, I'd prefer to discuss my use case in an open issue....

but basically automation - in the edge agent setup, the dual homed system will have its agents deployed using automation which doens't use swarm services, because the production systems don't use swarm mode.

**Comment by deviantony** [comment]
Sorry had trouble to figure out your use case yesterday ! 

From what I can tell, your feature request should actually be opened inside the Portainer repository (even if it is tied to the agent in your use case).

The reason is that the first Portainer do after connecting to an endpoint for management is to issue a request to retrieve the status of the engine associated to the endpoint (is it part of a Swarm). If the engine is part of a Swarm then Portainer will display the required management features.

As the agent is only a wrapper around the Docker API to provide a different way to connect to it as well as extra features, this feature request is not really related to the agent if I understand your use case correctly.

**Comment by SvenDowideit** [comment]
@deviantony - IDK maybe - I assumed it was the agent refusing to go through the motions of talking to portainer because it saw that docker was in swarm mode, and it didn't have the right cfg details to do swarm mode right.
